#!/bin/bash

while true; do
	read -p "Do you wish to remove all maintainer files [Y/n]? " yn
	case $yn in
		[Y]* ) break;;
		* ) exit;;
	esac
done

# dirs
rm -rf autom4te.cache/
rm -rf aux-dist/
rm -rf m4/
rm -rf src/.deps
rm -rf src/.libs
rm -rf src/*.lo
rm -rf src/*.la
rm -rf src/libtool
rm -rf src/toollib/.deps

# files
rm -f Makefile
rm -f Makefile.in
rm -f aclocal.m4
rm -f config.log
rm -f config.status
rm -f configure
rm -f include/Makefile
rm -f include/Makefile.in
rm -f libtool
rm -f src/Makefile
rm -f src/Makefile.in
rm -f src/toollib/*.la
rm -f src/toollib/*.lo
rm -f src/toollib/.dirstamp

echo "Cleaned files."
